In [119]:
import cv2
import pytesseract
import pandas as pd
import numpy as np
pytesseract.pytesseract.tesseract_cmd="C:\Program Files\Tesseract-OCR\\tesseract.exe"

img = cv2.imread('normal-blood.jpg')

text = pytesseract.image_to_string(img)

text = text.split('\n')
df = pd.DataFrame(text)
uncleaned_medical = df[4:].reset_index(drop=True)
uncleaned_medical[0].replace('',np.nan,inplace=True)
cleaned_medical=uncleaned_medical.dropna()

cleaned_medical.columns=['medical_report']

a=[]

for x in cleaned_medical['medical_report']:
    a.append(x.split())
clean_data = pd.DataFrame(a)
clean_data

            0    1       2     3        4          5
0        Urea  1.8       -   8.2   mmol/L       None
1   Potassium    3  mmol/L  None     None       None
2   Phosphate  0.8       -   1.4   mmol/L       None
3     Calcium  2.0       -   2.6   mmol/L       None
4  Creatinine   60       -   110   umol/L       None
5  Hemoglobin  120       -   140      g/L  (females)
6         140    -     160   g/L  (males)       None